// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace InfoClima.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WeatherForecast
    {
        /// <summary>
        /// Initializes a new instance of the WeatherForecast class.
        /// </summary>
        public WeatherForecast() { }

        /// <summary>
        /// Initializes a new instance of the WeatherForecast class.
        /// </summary>
        public WeatherForecast(string dateFormatted = default(string), int? temperatureC = default(int?), string summary = default(string), int? temperatureF = default(int?))
        {
            DateFormatted = dateFormatted;
            TemperatureC = temperatureC;
            Summary = summary;
            TemperatureF = temperatureF;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateFormatted")]
        public string DateFormatted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "temperatureC")]
        public int? TemperatureC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "summary")]
        public string Summary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "temperatureF")]
        public int? TemperatureF { get; private set; }

    }
}
